/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package protegemed.ui;

import java.util.Map;
import java.util.Map.Entry;

import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;

/**
 *
 * @author Joao Antonio Soares
 */
public class ProtegemedResults extends javax.swing.JDialog {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    /**
     * Creates new form ProtegemedResults
     */

    private Map<Integer, Map<String, String>> tableData;

    public ProtegemedResults(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Resultados");
        initComponents();
    }

    public ProtegemedResults(java.awt.Frame parent, boolean modal, Map<Integer, Map<String, String>> tableData) {
        super(parent, modal);
        setMinimumSize(new Dimension(850, 250));
        setMaximumSize(new Dimension(850, 250));
        setSize(new Dimension(850, 250));
        setModal(true);
        setResizable(false);
        setTitle("Resultados");
        setTableData(tableData);
        initComponents();
        fillTable(tableData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelResults = new javax.swing.JPanel();
        jScrollPaneResults = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneResults.setViewportView(jTableResults);

        javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneResults, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneResults, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProtegemedResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProtegemedResults dialog = new ProtegemedResults(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Map<Integer, Map<String, String>> getTableData() {
        return tableData;
    }

    public void setTableData(Map<Integer, Map<String, String>> tableData) {
        this.tableData = tableData;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JScrollPane jScrollPaneResults;
    private javax.swing.JTable jTableResults;
    // End of variables declaration//GEN-END:variables

    private void fillTable(Map<Integer, Map<String, String>> tableData) {
        DefaultTableModel model = (DefaultTableModel) jTableResults.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        Object[] columnNames = {"Tomada", "Usos", "Simultaneos", "Concorrentes", "Tempo de uso", "Tempo m\u00E9dio", "\"Liga\" descartados", "Erro de simultaneidade", "\"Desliga\" descartados", "Erro de simultaneidade"};
        model.setColumnIdentifiers(columnNames);

        for (Entry<Integer, Map<String, String>> entry : tableData.entrySet()) {

            Map<String, String> vLine = entry.getValue();

            Object[] line = {entry.getKey(), vLine.get("uses"), vLine.get("usesSimultaneous"), vLine.get("concurrentUsage"), vLine.get("usedTime"), vLine.get("avgUsedTime"), vLine.get("onError"), vLine.get("onErrorSimultaneous"), vLine.get("offError"), vLine.get("offErrorSimultaneous")};
            model.addRow(line);
        }

        jTableResults.setModel(model);

    }
}
